#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly SCRIPT_FULL_PATH="$(realpath "$0")"
readonly PROJECT_DIR="$(dirname "$SCRIPT_FULL_PATH")"
readonly TARGET_HOST=dietpi@192.168.129.250
readonly TARGET_PATH=/home/dietpi/hello_world/target/release/
# GLIBC mismatch between my (compilation) host and my target -> statically link
readonly TARGET_ARCH=arm-unknown-linux-musleabihf
readonly SOURCE_PATH="${PROJECT_DIR}/target/${TARGET_ARCH}/release/hello_world"

(command -V cargo 2> /dev/null > /dev/null) || source "${HOME}/.cargo/env"
env PATH="$HOME/build/armv6-linux-musleabihf-cross/usr/bin:$PATH" cargo build --release --target="${TARGET_ARCH}"
ssh ${TARGET_HOST} 'sudo systemctl stop rust-hello-world.service || echo Could not stop service, I hope everything is going to be OK'
tar cf - -C "$(dirname "${SOURCE_PATH}")" "$(basename "${SOURCE_PATH}")" \
    -C "${PROJECT_DIR}" templates/ assets/ \
    | ssh ${TARGET_HOST} "cd '${TARGET_PATH}'; tar xvf -"
ssh ${TARGET_HOST} 'sudo systemctl restart rust-hello-world.service'
